### ISSUE TITLE
Volunteer Maintainer

### ISSUE THREAD

**Issue by markroxor** [lee-dohm/language-r#11]
## :rotating_light: Attention :rotating_light:

I no longer use R in my daily work and haven't for a couple years. I also no longer have the time to maintain this package properly. If anyone is interested in taking over the maintenance of this package and eventually the repository, please post an [Issue](https://github.com/lee-dohm/language-r/issues/new) with the subject of "Volunteer Maintainer". Other Issues and PRs will be closed.

Hello there,
I have been using R for a while now and have recently been porting my python machine learning codes to R. I would like to maintain this repository. 
regards
markroxor

**Comment by lee-dohm** [comment]
Invited as collaborator. Thanks for volunteering!
