### ISSUE TITLE
Autocomplete plus R

### ISSUE THREAD

**Issue by guillaumechaumet** [lee-dohm/language-r#13]
I search support for building an autocomplete plus R. If someone understand something about autocomplete providers, it could really help (because I don't...).

**Comment by pimentel** [comment]
Would be nice to get this working. I'm thinking I might be able to dedicate some time to this mid-July.

**Comment by guillaumechaumet** [comment]
> PS: I have no idea how autocomplete works
Same here. I could not find a good tutorial.

**Comment by guillaumechaumet** [comment]
I made a first step: (don't work :D)
https://github.com/guillaumechaumet/autocomplete-R/

**Comment by guillaumechaumet** [comment]
It works! (almost)
