### ISSUE TITLE
Volunteer Maintainer

### ISSUE THREAD

**Issue by therimalaya** [lee-dohm/language-r#17]
## :rotating_light: Attention :rotating_light:

I no longer use R in my daily work and haven't for a couple years. I also no longer have the time to maintain this package properly. If anyone is interested in taking over the maintenance of this package and eventually the repository, please post an [Issue](https://github.com/lee-dohm/language-r/issues/new) with the subject of "Volunteer Maintainer". Other Issues and PRs will be closed.

I am working in R for few years and I am interested in making atom easy for R. I can be of some help.

**Comment by lee-dohm** [comment]
Invited as collaborator. Thanks for volunteering!

**Comment by therimalaya** [comment]
I am new with collaboration, git, github. But I will try to be useful. Thanks!

**Comment by lee-dohm** [comment]
Feel free to drop in on the [Atom Slack](https://discuss.atom.io/t/join-us-on-slack/16638) if you have any questions :grinning:
