### ISSUE TITLE
Feature request: rfmt integration

### ISSUE THREAD

**Issue by jzelner** [lee-dohm/language-r#18]
I've been using language-r and it's a life-saver for working with R within Atom! Thanks!

I've also been using the excellent rfmt code formatter (https://github.com/google/rfmt) and was wondering if there was any interest in creating hooks into it via Atom/language-r just like the bindings they've already put together for emacs and vim? Could even be via a shell command, but would be great to integrate into the language-r package.

**Comment by kylebarron** [comment]
This already exists in the [atom-beautify](https://github.com/Glavin001/atom-beautify) package. It uses Yihui Xie's [formatR](https://github.com/yihui/formatR) package.
