### ISSUE TITLE
Update atom packages page?

### ISSUE THREAD

**Issue by smsaladi** [lee-dohm/language-r#19]
Looks like there are a couple volunteer maintainers of this package now. Perhaps it would be good to update the atom package page reflecting that it's still maintained?

https://atom.io/packages/language-r

**Comment by kbsali** [comment]
:+1: ping @lee-dohm 

I was looking for a grammar package and found that one, but then started investigating the best alternative as it says it is un-maintained... which is apparently not the case any longer :)

**Comment by lee-dohm** [comment]
/cc @tpoisot @therimalaya @markroxor 

:point_up: These are the fine people that volunteered to maintain the package. They're the ones you should be addressing :grinning:

**Comment by pimentel** [comment]
ping @tpoisot @therimalaya @markroxor :)

If none of them respond, I can help out.

**Comment by markroxor** [comment]
I'm sorry, too much occupied with other libraries. @pimentel please go ahead

**Comment by pimentel** [comment]
No sweat. Can someone give me push privileges?


TIA
