### ISSUE TITLE
Folding and multi-line function headers

### ISSUE THREAD

**Issue by gaborcsardi** [lee-dohm/language-r#2]
Multi-line function headers are not folded properly:

```r
sim_expr_prof <- function(n, expr, bio_var=.2,
                          dir_param=rep(1, length(expr))) {
}
```

will only keep the first line when folded. I don't actually know if this is intended or not, I prefer seeing all arguments when folded.

**Comment by tpoisot** [comment]
Atom parses things line by line, so I'm not sure we will be able to get it right (easily, that is).

**Comment by lee-dohm** [comment]
I no longer use R in my daily work and haven't for a couple years. I also no longer have the time to maintain this package properly. If anyone is interested in taking over the maintenance of this package and repository, please post an [Issue](https://github.com/lee-dohm/language-r/issues/new) with the subject of "Volunteer Maintainer". Other Issues and PRs will be closed.
