### ISSUE TITLE
Volunteer Maintainer

### ISSUE THREAD

**Issue by OthaG** [lee-dohm/language-r#20]
Are you still soliciting volunteer maintainers?

**Comment by rgbkrk** [comment]
@lee-dohm ^^

I was about to post the same, though I'd love to see this get built in. I keep recommending Atom to R users, especially since they can use [hydrogen](https://github.com/nteract/hydrogen) for live coding in-app.

**Comment by lee-dohm** [comment]
Given that the last three contributors haven't been responding, I suppose that adding more would be the right thing. I'd prefer to see participation prior to granting push access though.

**Comment by guillaumechaumet** [comment]
By the way, there is 3 requests to pull. Anyone?
Cheers

**Comment by lee-dohm** [comment]
I'm not using R anymore, so I don't have an educated opinion on whether they're beneficial changes. Hence the need for volunteer maintainers. Or at least people to comment on the benefits and drawbacks of changes like those.

**Comment by guillaumechaumet** [comment]
I use R for a long time now and I'm always using R. However, I'm not a Git expert.

**Comment by pimentel** [comment]
I'm pretty busy this week, but would be happy to be a maintainer as well. I use this package pretty much every day

**Comment by fedevela** [comment]
Sign me up, although i am a total newbie to atom dev

**Comment by lee-dohm** [comment]
For the people that want to become maintainers, start commenting on PRs and/or submitting your own. I'll grant the rights to those who show they want to do the work.

**Comment by rgbkrk** [comment]
Awkwardly, I really only care that R just becomes a built-in for the sake of Hydrogen R users. I was literally at the GitHub offices demoing to some data scientists when I realized that I couldn't run R code without the language package installed.

Do you know what council I could approach with a request to make R a built in language?

**Comment by lee-dohm** [comment]
@rgbkrk, you can send an email to atom@github.com or create a topic on https://discuss.atom.io. The maintainer team (of which I am currently a member) will discuss it and get back to you. As of this writing, it is unlikely that the maintainer team would consider adding it. See [this recent issue](https://github.com/atom/atom/issues/13932) for background.

**Comment by lee-dohm** [comment]
This isn't something the Atom team wants to or has the expertise to maintain. Also, it has now been a few years since I've used R with any regularity at all, so I don't have the time or expertise to maintain this package either.

Given that the few people that have volunteered to maintain this package haven't picked up the banner here, I'm going to once again return this to unmaintained status. If anyone wants to take over maintenance, they can fork this package and create a new one.

**Comment by rgbkrk** [comment]
It does work as is, there aren't any open bugs are there?

**Comment by lee-dohm** [comment]
#18 was open still. And #15, #16, #22, and #23 were open.
