### ISSUE TITLE
moving to REditorSupport

### ISSUE THREAD

**Issue by randy3k** [lee-dohm/language-r#25]
Hi @lee-dohm 

It is pity that you are no longer supporting this. @Ikuyadeu (author of VSCode R package) and I (author of Sublime Text R package) have recently created an organization: https://github.com/REditorSupport
And we have an idea to transfer our packages, [R-Box](https://github.com/randy3k/R-Box) and [vscode-R](https://github.com/Ikuyadeu/vscode-R?files=1) to the organization and use Language Server Protocol to provide the language support on those platforms. The transfer of R-Box will happen when the language server for R is ready.

I am just wondering if you will be also interested in transferring this to the organization. Although I cannot guarantee that much, with the language server that we are developing and [atom-languageclient](https://github.com/atom/atom-languageclient). At least there will be some minimum support for the R language in Atom, better than being stale in this repo.

**Comment by randy3k** [comment]
I have just invited you to the organisation just in case you want to transfer the package to there.

**Comment by lee-dohm** [comment]
Thank you very much for the offer.

Whether this repo lives here or in @REditorSupport, I simply don't have the time or expertise to maintain it anymore. It is better if someone else who is actively using R takes up the effort. If you or @ikuyadeu are interested in taking this on, please feel free to fork the code from here as a starting point.

**Comment by randy3k** [comment]
I am inviting you to join because I also want to inherit the package name on atom.io: https://atom.io/packages/language-r
If we fork your repo, we probably need to use a different name and it is less desirable unless there is a way to overtake a deprecated package on atom.io.

**Comment by lee-dohm** [comment]
There isn't a way to forcibly take over someone else's package. A package can be transferred by [transferring the underlying repository.](http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#transferring-ownership) I could do that, but it doesn't sound like anyone is really signing up to take on maintenance of the package?

**Comment by randy3k** [comment]
I have a plan to at least implement the R language server on atom. It doesn't seem to be very hard 
to use [language client](https://github.com/atom/atom-languageclient) once the R language server is ready to ship.

If you and (other phantom collaborators) don't mind, I will be happy to take over it at REditorSupport. Given that it is very likely that @Ikuyadeu and I will continuously support vscode and sublime text (plus the language server). Transferring it to an umbrella organization may be a better choice than waiting for somebody to fork the repo.

**Comment by randy3k** [comment]
By the way, if you don't wan to transfer it now. We can wait until @Ikuyadeu and I have done more work at REditorSupport. And I will come back to you a bit later when I am ready to implement the language server on Atom.

**Comment by lee-dohm** [comment]
> We can wait until @Ikuyadeu and I have done more work at REditorSupport.

Thanks. Given my experience with adding collaborators here, I'd rather base my decision on concrete progress than people's stated plans :grinning:

**Comment by randy3k** [comment]
Totally understood.

**Comment by guillaumechaumet** [comment]
Nice project @randy3k. I made an attempt to produce a [autocomplete](https://github.com/guillaumechaumet/autocomplete-R) package for R. Perhaps we could collaborate together to improve communication between R and atom-io.

**Comment by randy3k** [comment]
For the atom R support, my plan is to move it to language server protocol so it will be easier to be maintained across different editors. Feel free to implement [languageserver ](https://github.com/REditorSupport/languageserver) via atom [language client](https://github.com/atom/atom-languageclient). 

I guess if we could show our commitment, @lee-dohm will be more confident to transfer `language-r` to REditorSupport.

**Comment by randy3k** [comment]
Though, I should have added that the language server is not ready yet. Only code diagnostic is implemented.

**Comment by kylebarron** [comment]
Hi @lee-dohm  and @randy3k ,

Over the summer I saw the calls for a volunteer maintainer, and would have replied but wanted to have some proof of work first. I completely rewrote the Stata [language package](https://atom.io/packages/language-stata) (another statistical package heavily used by economists) and the maintainers of the previous package decided to make mine the main one in Atom. 

I'm 23 commits into an [update](https://github.com/kylebarron/language-r) of language-r. The main areas for improvement I've been working on are better highlighting of function calls and regular expression highlighting. I had hoped to ask to be a volunteer maintainer upon finishing my updates and submitting a large PR. I find less utility in making a _language-r-plus_ package in Atom that's hard to find and has relatively small probability of getting off the ground, user-base wise.

@randy3k keep me in the loop if you fork the language package to REditorSupport, and I'd be happy to collaborate on the fork there, if desired.

**Comment by randy3k** [comment]
@kylebarron 
I have pushed  a temporary repo for [atom-language-r](https://github.com/REditorSupport/atom-language-r) and invited you to REditorSupport. Please feel free to push to it.

PS: I intentionally do not "fork" this repo so @lee-dohm can transfer this repo to REditorSupport later.

**Comment by randy3k** [comment]
@guillaumechaumet

I have also invited you to the project.
