### ISSUE TITLE
Support for .Rnw .Rmd files

### ISSUE THREAD

**Issue by pankil-shah** [lee-dohm/language-r#5]
Please add support for the .Rnw and .Rmd files

**Comment by pankil-shah** [comment]
My first impression is that a separate grammar file adapted from the markdown language needs to be created. then using `'''` as a anchor for start and end of the R code nested within the markdown can be formatted differently using maybe

    atom-text-editor::shadow .embedded {
    ...

to give a different background and the grammar from the R language.

In fact, the opacity effects might be used to make the text vs r code visible alternately. That would be great for long documents.

I'm new to atom and can't do this myself, but am happy to collaborate if this peaks your interest.

**Comment by pimentel** [comment]
hello @pankil-shah I too am very interested in this feature. have you made any progress on it?

I might look into it in my "spare time" soon as it has become pretty important recently.

**Comment by lee-dohm** [comment]
I apologize that it has taken so long for me to comment here.

I'm not sure that a separate grammar file needs to be created. The [default-installed language-gfm package](https://github.com/atom/language-gfm) already supports embedding many languages within a Markdown file. It would just be a question of adding support for syntax-highlighting R code blocks inside a Markdown file much like it supports syntax-highlighting JavaScript code blocks inside the Markdown file. Here is where the language-gfm package adds support for JavaScript code blocks:

https://github.com/atom/language-gfm/blob/d8871b1efebfd1b2c91b284fda2a83d6b132fa76/grammars/gfm.cson#L218-L234

**Comment by pimentel** [comment]
Thanks for responding, @lee-dohm.  This looks pretty trivial. I will try to do it this week.

**Comment by pankil-shah** [comment]
@lee-dohm - Thanks for the reply.
@pimentel - Thanks for following up. Let us know how it goes.

**Comment by pankil-shah** [comment]
Sorry, Closed the issue accidentally.

**Comment by pimentel** [comment]
I made a pull request to the `language-gfm` people: https://github.com/atom/language-gfm/pull/130 it's not as smart as one would like (look at the pull request) but it is working for a first pass.

I looked at `language-latex` and I think it is a bit more complicated than Rmd, at least to conform to their style. They seem to do something pretty cool for `lstlisting` which could definitely work for Rnw files, I don't fully grok it yet. I think something like that approach would be doable as well in `language-gfm` to make the different engines work.

The other option is to recursively insert those grammar files into `language-r` like they do in `language-latex` for beamer: https://github.com/area/language-latex/blob/master/grammars/latex%20beamer.cson That way we can maintain our own little nuances without polluting their packages. Just a thought.

**Comment by pimentel** [comment]
I forgot to note, the `language-latex` repository seems to be pretty inactive which is also another reason to consider including Rnw support here. Though, someone else might have to do it because I don't think I will have time in the near future (it's a bit more complicated and I need to do a bit of learning).

**Comment by pimentel** [comment]
@pankil-shah fyi, `language-gfm` has been updated and now supports RMarkdown blocks.

**Comment by pankil-shah** [comment]
@pimentel Awesome. great work. I'll test is out and close the topic once done.
Thanks again.

**Comment by pimentel** [comment]
@pankil-shah you should also check out `language-markdown`. The author has been very receptive and is slowly adding in lots of cool features (like correctly displaying the language given different `engine=` arguments)

**Comment by lee-dohm** [comment]
I no longer use R in my daily work and haven't for a couple years. I also no longer have the time to maintain this package properly. If anyone is interested in taking over the maintenance of this package and repository, please post an [Issue](https://github.com/lee-dohm/language-r/issues/new) with the subject of "Volunteer Maintainer". Other Issues and PRs will be closed.
