### ISSUE TITLE
recognizing R symbols/functions

### ISSUE THREAD

**Issue by dtenenba** [lee-dohm/language-r#8]
Not sure if it's the job of this package, but when I have an .R file open and I type command-R, I don't see a list of R functions. In sublime text, I would.

**Comment by pimentel** [comment]
an easy way to get such a list is to use `atom-ctags`

**Comment by dtenenba** [comment]
Doesn't work. In fact after installing it a message pops up (can't get it to pop up again so I can't say what it was verbatim) saying that symbol lookup is overridden by atom-ctags and therefore disabled. And command-R still shows no symbols in an R source file.

**Comment by lee-dohm** [comment]
@dtenenba You are correct. It isn't the job of this package. The built-in [symbols-view package](https://atom.io/packages/symbols-view) is responsible for this behavior. You can find the configuration file that it uses here: https://github.com/atom/symbols-view/blob/master/lib/ctags-config
