### ISSUE TITLE
Hope for sending lines to Rstudio instead of R.app

### ISSUE THREAD

**Issue by evanzhu2013** [lee-dohm/language-r#9]
Hope for sending lines to Rstudio instead of R.app just like R-box in the Sublime Text 3. 

I appreciate your work for R.

**Comment by lee-dohm** [comment]
I no longer use R in my daily work and haven't for a couple years. I also no longer have the time to maintain this package properly. If anyone is interested in taking over the maintenance of this package and repository, please post an [Issue](https://github.com/lee-dohm/language-r/issues/new) with the subject of "Volunteer Maintainer". Other Issues and PRs will be closed.
